# Generated by Django 5.2.6 on 2025-09-17 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(max_length=10, verbose_name="Código do Ativo"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Médio"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Ação", "Ação"),
                            ("FII", "Fundo Imobiliário"),
                            ("Renda Fixa", "Renda Fixa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ativo",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Setor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
                "unique_together": {("user", "ticker")},
            },
        ),
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data de Pagamento")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Recebido"
                    ),
                ),
                (
                    "dividend_type",
                    models.CharField(
                        choices=[
                            ("Dividendo", "Dividendo"),
                            ("JCP", "Juros sobre Capital Próprio"),
                            ("Rendimento", "Rendimento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Provento",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="portfolio.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provento",
                "verbose_name_plural": "Proventos",
                "ordering": ["-date"],
            },
        ),
    ]
