# Generated by Django 5.2.6 on 2025-09-17 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Alvo"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("ABOVE", "Acima de"), ("BELOW", "Abaixo de")],
                        max_length=10,
                        verbose_name="Condição",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("TRIGGERED", "Acionado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="portfolio.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Preço",
                "verbose_name_plural": "Alertas de Preços",
                "ordering": ["-created_at"],
            },
        ),
    ]
