# Generated by Django 5.2.6 on 2025-09-18 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="annual_dividend_projection",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor total de dividendos esperado para os próximos 12 meses por cada ação/cota.",
                max_digits=10,
                null=True,
                verbose_name="Projeção de Dividendo Anual (R$ por Ação)",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desired_yield",
                    models.DecimalField(
                        decimal_places=2,
                        default=6.0,
                        max_digits=5,
                        verbose_name="Yield Mínimo Desejado (%)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
